---
- name: Install Memcached
  apt: name=memcached state=present

- name: Install Memcached Configuration
  template: src='../templates/memcached.conf.j2' dest='/etc/memcached.conf'
  notify:
  - Restart Memcached
